production:
  adapter: redis
  url: <%= ENV["REDISCLOUD_URL"] %>
development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: Friends_production
adapter: redis
url: YOUR_URL
